### ISSUE TITLE
JSend output don't look like JSend

### ISSUE THREAD

**Issue by mtancoigne** [CakeDC/cakephp-api#11]
As per [this example](https://labs.omniti.com/labs/jsend), the model for each dataset is sent in the response:
```json
{
    status : "success",
    data : {
        "post" : { 
            "id" : 1, "title" : "A blog post", "body" : "Some useful content"
        }
     }
}
```

For now the JSend renderer outputs:
```json
{
    status : "success",
    data : {
        "id" : 1, "title" : "A blog post", "body" : "Some useful content"
     }
}
```

I managed to loop through the dataset in the `JsendRenderer`, but I don't think that's where the code belongs to.
Where is the best place to change the output formatting when it needs data from the <Model>Table classes ?

**Comment by skie** [comment]
JSend mainly defines the message and data presense in response and the status code for responses. Content of data response is flexible, and its semantic depends of backend that uses it. For this plugin most sense is reflect structures that cakephp3 ORM represents.

**Comment by mtancoigne** [comment]
@skie Ok, so let's close this, as its not a real JSend format issue.
