### ISSUE TITLE
Does not work out of the box with most recent cakedc/users plugin

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/cakephp-api#25]
└──╼ composer require cakedc/cakephp-api
     Using version ^3.3 for cakedc/cakephp-api
     ./composer.json has been updated
     Loading composer repositories with package information
     Updating dependencies (including require-dev)
     Your requirements could not be resolved to an installable set of packages.

       Problem 1
         - Installation request for cakedc/cakephp-api ^3.3 -> satisfiable by cakedc/cakephp-api[3.3].
         - cakedc/cakephp-api 3.3 requires cakedc/users ^4.0 -> satisfiable by cakedc/users[4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.2.1, 4.x-dev] but these conflict with your requirements or minimum-stability.

     Installation failed, reverting ./composer.json to its original content.

In my composer.json, I have 

    "cakedc/users": "^5.0",

If you were going to update this api plugin right now, how would you go about doing it.. just type out a bullet list of things you would do and I will attempt to get it done, I just need someone to point me in the right direction

**Comment by jeffreyroberts** [comment]
I see that the composer.json in the git repo is ^5.0, something screwy with packagist maybe?

**Comment by jeffreyroberts** [comment]
I got it to work with

    composer require cakedc/cakephp-api:dev-master

however, that is not what is in, https://github.com/CakeDC/cakephp-api/blob/master/docs/Documentation/installation.md

**Comment by skie** [comment]
fixed now
