### ISSUE TITLE
I could really use an example project

### ISSUE THREAD

**Issue by jeffreyroberts** [CakeDC/cakephp-api#29]
I could really use a simple example project, maybe one that showcases each feature? I am glad to help, I will even get it started under my own repo's if you want, just thought I would see if you would prefer to have the example repo under CakeDC as more people will find it there...

**Comment by skie** [comment]
There is https://github.com/gothinkster/cakephp-realworld-example-app that based on this plugin.

**Comment by jeffreyroberts** [comment]
sweet, thank you!
