### ISSUE TITLE
DashedRoute routing?

### ISSUE THREAD

**Issue by thumbtech** [CakeDC/cakephp-api#41]
I can't figure out how to get the default API routing to use dashedRoute.

For example, using the cakephp-api-example repo, if my "posts" table were "blog_posts" (and the table & entity classes were appropriately renamed BlogPostsTable / BlogPost, etc.), I would wish to access the api via host/api/blog-posts instead of host/api/blog_posts. If I bake controller & templates for BlogPosts, it lights up as expected under host/blog-posts.

Perhaps this would be explained under Routing in docs, but this returns 404 ... ?

**Comment by skie** [comment]
PR merged
