### ISSUE TITLE
Cannot set response status code

### ISSUE THREAD

**Issue by birdy247** [CakeDC/cakephp-api#46]
I have tried setting the response code to something other than a 200.

What I tried:

In an Action

$response = $this->getService()->getResponse();
$this->getService()->setResponse($response->withStatus(404));

The response is still always a 200

**Comment by skie** [comment]
Seems, you are using JsendRenderer. Jsend by specification suppose to return always 200 response code.

**Comment by birdy247** [comment]
@skie thanks, so what is the correct way to set the status to fail within an action?

**Comment by skie** [comment]
You can switch to Json renderer or create custom renderer.

**Comment by skie** [comment]
Like I said you should be able to overload Jsend class and add needed functionality.
