### ISSUE TITLE
$this->getData() is always empty

### ISSUE THREAD

**Issue by birdy247** [CakeDC/cakephp-api#47]
On latest version of cakeapi

When we inspect $this->getData(), it is always an empty array (for POST, PUT)

We have to use this to retrieve the request payload:

$data = $this->getService()->getRequest()->input('json_decode', true);

request url /myapp/api/v1/example

headers: 
'Content-Type': 'application/json',
'Accept': 'application/json'

**Comment by skie** [comment]
Do you including RequestHandlerMiddleware before ApiMiddleware.

**Comment by skie** [comment]
No, that's all you need.
