### ISSUE TITLE
problems with api

### ISSUE THREAD

**Issue by tgoeminne** [CakeDC/cakephp-api#63]
I try to use this plugin but it is giving me some problerm:

I have

Service/v1/ArticleService.php

<?php 
namespace App\Service\v1;

use CakeDC\Api\Service\Service as Service;

class ArticleService extends Service {

    protected $_actionsClassMap = [
        'describe' => '\CakeDC\Api\Service\Action\CrudDescribeAction',
        'index' => '\App\Service\v1\Action\Articles\IndexAction',
        'view' => '\App\Service\v1\Action\Articles\ViewAction',
        'add' => '\App\Service\v1\Action\Articles\AddAction',
        'edit' => '\App\Service\v1\Action\Articles\EditAction',
        'delete' => '\App\Service\v1\Action\Articles\DeleteAction',
    ];
  
}

Then in the files Service\v1\Action\Articles\IndexAction

<?php 
namespace App\Service\Action\Articles;

use CakeDC\Api\Service\Action\CrudIndexAction;

class IndexAction extends CrudIndexAction {

    public function execute()
    {
        $results = $this->_getEntities();
        
        return $results;
    }
 
}

Then everything I try to visit everywhere it says a route matching articles can not be found

**Comment by tgoeminne** [comment]
`<?php 
namespace App\Service\v1;

use CakeDC\Api\Service\Service as Service;

class ArticlesService extends Service {

    protected $_actionsClassMap = [
        'describe' => '\CakeDC\Api\Service\Action\CrudDescribeAction',
        'index' => '\App\Service\v1\Action\Articles\IndexAction',
        'view' => '\App\Service\v1\Action\Articles\ViewAction',
        'add' => '\App\Service\v1\Action\Articles\AddAction',
        'edit' => '\App\Service\v1\Action\Articles\EditAction',
        'delete' => '\App\Service\v1\Action\Articles\DeleteAction',
    ];
    
    
}`

Then 


`<?php 
namespace App\Service\Action\Articles;

use CakeDC\Api\Service\Action\CrudIndexAction;

class IndexAction extends CrudIndexAction {

    public function execute()
    {
        $results = $this->_getEntities();
        
        return $results;
    }
 
}`


{"status":"error","message":"A route matching \"\/articles\" could not be found.","code":404,"data":null}

**Comment by skie** [comment]
Is versions enabled in config/api.php?

**Comment by tgoeminne** [comment]
yes

**Comment by tgoeminne** [comment]
When I use FallbackService instead of service I can access /api/v1/articles and then it works, but then also the actions view,... does not work (missing routes). When I use Service, I can not even access /api/v1/articles (missing route). In my other post I also mention the config, I have to put vv1 in the config files so that the version config is loaded when request v1 on fallbackservice...

**Comment by skie** [comment]
i would create `class ArticlesService extends FallbackService `  and overload only needed actions. Also I recommend to take  look on https://github.com/gothinkster/cakephp-realworld-example-app

**Comment by tgoeminne** [comment]
I just use actionsClassMap and then use execute method in the action. Is that not enough to get it to work?

**Comment by tgoeminne** [comment]
Everything just show missing routes when I use api/articles/view/1, if I use versioning or not, this plugin another type of give me a serious headache to try it to get to work.... also the documentation seriously lacking as usual. Did you see the link to routes is pointing to 404?

**Comment by skie** [comment]
you used Service not CrudService or FallbackService

**Comment by tgoeminne** [comment]
with fallbackservice is the same, it doesn't work.

**Comment by tgoeminne** [comment]
Feels like the plugin is designed to give people problems doing something so simple. It is really terrible piece of code.

**Comment by steinkel** [comment]
@tgoeminne this plugin has some defaults and conventions that may not match what you usually do or expect in your project. I've used it many times, and it provides what I usually need when dealing with an API project. I understand you could be frustrated because it does not work as you expect though. 

What contributions could you do to improve the docs or the code so other users could benefit from them?

I see @skie is already taking some time to help you... maybe this could become an input for the documentation later for other users trying to do the same you're doing here?

Thanks,

**Comment by tgoeminne** [comment]
I am looking at it now. I thought it would be more easy to have the request go to /api/articles/view/18 then to api/articles/18

Need to look into it more, but is pretty confusing. Is there somewhere code or like an sdk that an end user would use on third party php website to access the api?

**Comment by tgoeminne** [comment]
```
$actions = [
            'index' => $reverseRouter->link('self', $path, 'GET'),
            'add' => $reverseRouter->link('add', $path, 'POST'),
            'edit' => $reverseRouter->link('edit', $path . '/{id}', 'PUT'),
            'delete' => $reverseRouter->link('delete', $path . '/{id}', 'DELETE'),
        ];
```

**Comment by tgoeminne** [comment]
I also see that you can use cakdc users to authorize, but I can not find any documentation on how to do this. Both for sending the request and setting it up.

I am sending post request and I get csrf token missing...

There is a link to jwt tutorial which also goes to a 404 page...

**Comment by skie** [comment]
Api plugin is 100% RESTful. So routes based on REST verbs and urls based on REST convetions. So correct there would be GET, /articles for index, and GET,/articles/:id for view, POST,/articles for add, and PUT,/articles/:id for edit, and finally DELETE,/aritcles/:id for delete.

**Comment by delamux** [comment]
> I also see that you can use cakdc users to authorize, but I can not find any documentation on how to do this. Both for sending the request and setting it up.
> 
> I am sending post request and I get csrf token missing...
> 
> There is a link to jwt tutorial which also goes to a 404 page...

Sorry, meaby the link is broken on the main documentation.

https://github.com/CakeDC/cakephp-api/blob/master/docs/Documentation/Auth/jwt.md

**Comment by tgoeminne** [comment]
Is there somewhere a tutorial how to do the api request with auth via cakedc users? And also so it works with csrf and such...?

**Comment by delamux** [comment]
Hello @tgoeminne, I don't know I this repo can Help you I did it last year.

https://github.com/delamux/apiplug

**Comment by skie** [comment]
https://www.cakedc.com/yevgeny_tomenko/2020/06/29/cakedc-api-plugin-authentication-and-authorization

**Comment by tgoeminne** [comment]
I am using basic token authorization for now. where you add ?token=xxxxx to the back

I am running in the problem with request POST being blackholed due to missing csrf token. How can you disable csrf token in service/action?

**Comment by tgoeminne** [comment]
Then disable the csrf middleware by changing routes and application.php. Now the POST request being blackholed.

**Comment by steinkel** [comment]
is SecurityComponent enabled for these actions?

The way to disable Csrf is creating a specific routing scope "without" loading the csrf middleware into it.

**Comment by tgoeminne** [comment]
Yes I disabled csrf, now looking how I can dissable security component for specific action. I thought the point of mapCors was that it is allowed by default from another domain, but it seems it isn't working like that. 

I try put this in Articleservice but not work
`
public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        
        $this->Security->setConfig('unlockedActions', ['add']);
    }
`

**Comment by steinkel** [comment]
That should not be an issue if you plug Api using the https://github.com/CakeDC/cakephp-api/blob/master/src/Middleware/ApiMiddleware.php

**Comment by tgoeminne** [comment]
How do I do that?

**Comment by steinkel** [comment]
https://github.com/gothinkster/cakephp-realworld-example-app/blob/master/src/Application.php#L102

Example there ^

**Comment by tgoeminne** [comment]
Where do I insert that then? There is nowhere any information about this in the docs or configuration/installation... Why is this so complicated to get it to work properly?

**Comment by steinkel** [comment]
We need to properly document the Api middleware load, you're right.

I understand the specific problem is Security component interacting with your ApiController, so I would suggest either:
* Setup ApiMiddleware to ignore the controller layer and bypass Security
* Properly configure Security, for example in your AppController, check if the request belongs to the Api and disable SecurityComponent.

**Comment by tgoeminne** [comment]
`if(!$this->getRequest()->getAttributes()['params']['controller'] == 'Api'){
            $this->loadComponent('Security');
        }`

**Comment by tgoeminne** [comment]
Now when I post I receive another error: 

{"error":{"code":422,"message":"Validation failed","validation":{"version":{"_required":"This field is required"}}}}

**Comment by tgoeminne** [comment]
I have set useVersioning to false, then why is this field required?

**Comment by tgoeminne** [comment]
I don't understand why Api is considered a "controller", when it should really just be a "prefix"...

**Comment by tgoeminne** [comment]
Ok I got it to work now after disabling both csrf and security for api controller.

**Comment by tgoeminne** [comment]
I would have probably been better of just making a prefix api and then send response with json....

**Comment by tgoeminne** [comment]
I have a question about the post data adding of files. What is the best way to send files to api? I am using cakephp upload...

**Comment by steinkel** [comment]
Hi, posting a file is the same as posting any other data, the tmp file will be available in the request and using upload or any other plugin to manage the posted data will process the file and move it somewhere else in your backend. Are you facing any specific issue while dealing the the uploaded files?

Thanks,

**Comment by tgoeminne** [comment]
Still need to test it..

**Comment by tgoeminne** [comment]
Hi,

I am sending postwithmultipartformdata to api and then when I do print_r on $this->getData() to debug log. I can see 


    [--------------------------d1f95fef5s642baf
Content-Disposition:_attachment;_name] => "test.json"; filename="test.json"
Content-Type: application/octet-stream

and then json contents.

If I understand correctly in this case $this->getData() is a file? Then how do I get the actual json data in an array?

**Comment by skie** [comment]
Possible you want to define custom RequestParser inherited from Api\Service\RequestParser\BaseParser or just want access to request object with $this->getService()->getRequest()

**Comment by tgoeminne** [comment]
I do getData but I see content disposition inthere which is normally a header?

**Comment by skie** [comment]
closed as obsolete support issue
