### ISSUE TITLE
All errors are returned with [status code 200 OK] in the response header. It should return the real status code of the exception.

### ISSUE THREAD

**Issue by mproenza** [CakeDC/cakephp-api#68]
When an exception occurs during an API call, **the Status response header always returns with 200 OK**, which is not appropriate for exception handling on the client code.

**_NOTICE_: I tested this only with JSendRenderer.**

The json response DOES contain an entry with the status code, like:

    {
        "status": "error",
        "message": "Forbidden authorization request",
        "code": 403
    }

But the status header should also contain the real status for convenience in the client code.

**What's wrong in the CakeDC/Api code?**

**On line 115 in _JSendRenderer_**, inside the _error()_ function, the line goes like:

    ->withStatus((int)$this->errorCode)

The problem is that **_$this->errorCode_ is NEVER updated with the actual exception code** (and never updated at all inside _JSendRenderer_), so **it always equals 200**.

I think the line should be:

    ->withStatus((int) $exception->getCode())

Or otherwise add `$this->errorCode = $exception->getCode();` before building the response.

That way the status header would return with the real status code.

**Comment by mproenza** [comment]
PROVISIONAL SOLUTION: Create a new JSend Renderer and config the plugin to use it.

**In src/Service/Renderer/ExtendedJSendRenderer.php**:

    <?php
    namespace App\Service\Renderer;

    use CakeDC\Api\Service\Renderer\JSendRenderer;
    use Exception;

    class ExtendedJSendRenderer extends JSendRenderer {

        public function error(Exception $exception): void
        {
            parent::error($exception);

            $this->errorCode = $exception->getCode();

            $response = $this->_service->getResponse();
            $response = $response->withStatus((int) $this->errorCode);

            $this->_service->setResponse($response);
        }
    }

**In config/api.php**:

    return [

        'Api' => [

            'renderer' => ExtendedJSendRenderer::class,
        ]
    ]

**Comment by skie** [comment]
Jsend specification supposed to have 200 status ALWAYS.
Use Json renderer if you want requested behavior.
