### ISSUE TITLE
JWT tokens not authorizing until a minute after refresh

### ISSUE THREAD

**Issue by SplicePHP** [CakeDC/cakephp-api#75]
Hi, I don't know if anyone else is having this issue.
After a response from the refresh token I get forbidden access until about a second after the token was refreshed.
In CakeDC\Api\Service\Action\Auth\JwtTokenTrait around line 40 inside the generateTokenResponse method the line reads:
`$timestamp = new DateTimeImmutable();`
setting it to:
`$timestamp = new DateTimeImmutable('-1 second');`
fixes the issue.

**Comment by skie** [comment]
Have you checked that time on php server and database server is same?

**Comment by skie** [comment]
Closed as not reproduced.
