### ISSUE TITLE
API Route on my own service dosn't work

### ISSUE THREAD

**Issue by jreiher** [CakeDC/cakephp-api#76]
I try this form our documentation (service.md)

```
use App\\Posts\\FlagAction;

    public function initialize()
    {
        parent::initialize(); 
        $this->mapAction('flag', FlagAction::class, [
            'method' => ['POST'],
            'mapCors' => true,
            'path' => ':id/:flag'
        ]); 
    }
```
message: A route matching "/flag/1/myflag" could not be found. on line 199 in .../vendor/cakephp/cakephp/src/Routing/RouteCollection.php

I take a look into method "mapAction" if $route['path'] is set then the actionName will be missing.

Here my work arround:
```
use App\\Posts\\FlagAction;

    public function initialize()
    {
        parent::initialize(); 
        $this->mapAction('flag', FlagAction::class, [
            'method' => ['POST'],
            'mapCors' => true,
            'path' => 'flag/:id/:flag'
        ]); 
    }
```
Is it wanted like that?

**Comment by skie** [comment]
Take a look into https://github.com/gothinkster/cakephp-realworld-example-app/blob/master/src/Service/ProfilesService.php 
I suppose you need to define correct regex for id and for flag

**Comment by skie** [comment]
One more note. Dont forget that your real url should be prefixed with service name too

**Comment by skie** [comment]
Do you have more questions?

**Comment by jreiher** [comment]
Not at this moment. Sorry, the time passed very quickly, we a new project.
Thanks for the tip on the real world example. I have found everthing what i need.

Thank You
