### ISSUE TITLE
Note about JSend being the default renderer

### ISSUE THREAD

**Issue by ravage84** [CakeDC/cakephp-api#8]
While it is [stated deep in the documentation tree](https://github.com/CakeDC/cakephp-api/blob/master/docs/Documentation/Renderers/jsend.md), that JSend is the default renderer, it is nowhere mentioned anywhere else.

It should be noted in the appropriate section in the [overview](https://github.com/CakeDC/cakephp-api/blob/master/docs/Documentation/overview.md#renderers) already.

Also it should be shown how to change the default renderer in the [config docs](https://github.com/CakeDC/cakephp-api/blob/master/docs/Documentation/configuration.md).

**Comment by steinkel** [comment]
I agree, thank you for pointing that out

**Comment by skie** [comment]
added to overview.md
