### ISSUE TITLE
Disabling public access

### ISSUE THREAD

**Issue by rudy1976s** [CakeDC/cakephp-api#91]
I have followed doc to completely disable public access of crud api: 

- loaded plugin in Application.php
- loaded api.php configuration file
- removed the following line from api.php configuration file:

` 'allow' => '*', // PUBLIC ACCESS for all API endpoints, remove this line to secure
`

but this is not working because my api are stille visible and open without any authentication

I would need to secure my api using url token and/or JWT

Do you have a walkthough for setup all needed part ?

Thank you

Rudy

**Comment by skie** [comment]
If in this demo app https://github.com/CakeDC/cakephp-api-cake4-demo
you will put into config/api_permissions.php next content
```php
<?php
return [
    'CakeDC/Auth.api_permissions' => []
];
```
you will got 
```json
{
    "status": "error",
    "message": "Forbidden authorization request",
    "code": 403,
    "data": null
}
```

So, the demo app configured in the way it is passing all requests through authentication and authorization middlewares using router level middlewares. If you need to use jwt, you need to add to api.php next section
```
        'Jwt' => [
            'enabled' => true,
            'AccessToken' => [
                'lifetime' => 1200,
                'secret' => 'some secret token',
            ],
            'RefreshToken' => [
                'lifetime' => 2 * WEEK,
                'secret' => 'secret token',
            ],
        ],

**Comment by skie** [comment]
Closed because of no reaction.
