### ISSUE TITLE
Unable to call method validateUnique in table provider for field username

### ISSUE THREAD

**Issue by giteugenio** [CakeDC/cakephp-api#99]
I'm using v9.1.0 migrating from v7.x without much problems :-), but in that case the cake bake command for the UsersTable generated a validator and a Rule layers for unique field username. Both can't stay together in my code because fails as you can see below in new user entity (auth/register action). This just happens when i config in CakeDC/Users plugin my own table extending the plugin model table.

`class UsersTable extends PluginUsersTable`
```
$validator
    ->scalar('username')
    ->maxLength('username', 255)
    ->requirePresence('username', 'create')
    ->notEmptyString('username');
    // ->add('username', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);
    // para que no se repita el username no utilizar un validador, sino una regla (abajo) - DA PROBLEMAS AL REGISTRAR USUARIO   
```

```
public function buildRules(RulesChecker $rules): RulesChecker
{
    $rules->add($rules->isUnique(['username']), ['errorField' => 'username']);
```

**[I attached the debug code]**
[error_provider_isUnique_cakephp_api.txt](https://github.com/CakeDC/cakephp-api/files/11165163/error_provider_isUnique_cakephp_api.txt)

**Comment by arodu** [comment]
It seems that this is an issue with the users plugin, or is there something about cakephp-api that I don't see?

**Comment by giteugenio** [comment]
Sorry, i realized that this is a normal behaviour in cakephp for validators and rules.
